### ISSUE TITLE
Please add reference to 'profiles/profiles.desc' to repoman's manpage

### ISSUE THREAD

**Issue by Coacher** [gentoo/portage#21]
Hello.

'man repoman' suggests there exist 'dev' and 'exp' profiles, but doesn't say where those are specified.
It would be useful to mention 'profiles/profiles.desc' file, so people who don't know this yet could learn it immediately from manpage.

**Comment by floppym** [comment]
You should submit this as a bug report on bugs.gentoo.org.

https://bugs.gentoo.org/enter_bug.cgi?product=Portage%20Development&component=Repoman
